#Verificacao do erro esta na propria classe Pessoa
from models import *
perfis = Perfil.gerar_perfis('arquivo_novo.csv')
